# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0a980df0dc874cd399c412c652720aea2f983c9d07b5956de65bb943b6d6f6eb5bc6a9754ffe9e8364e9dbe1be2a1bccc7accba4d31c4014757781dc4530167

test:
  secret_key_base: d76d55dba9275138702e57539f4bd92cbf894665d75b2b0d241a1e0ffb876c92bd54172ae5af994581a60c19e612052f24eaaa0a3818ec09fdc41b0198c56a9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
